import "../styles/globals.css";
import "../sass/home.scss";
import Header from "@/components/header/Header";
import Link from "next/link";

export const metadata = {
  title: "Faruq Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const footer = (
    <footer>
      <div className="border-t border-slate-500 mt-6 py-6 text-center text-slate-400">
        <p>
          Copyright 2023 &#169; <Link href={"/"}>Faruq Blog</Link>
        </p>
      </div>
    </footer>
  );
  return (
    <html lang="en">
      <head />
      <body className="">
        <Header />
        <div className="mx-auto w-full max-w-5xl ">
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
